// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6zCE04v7xPqj3X0gnQhq-sGEEEVRgjE',
    appId: '1:957207033721:web:2487012672d3e9cc6921a8',
    messagingSenderId: '957207033721',
    projectId: 'book-buds',
    authDomain: 'book-buds.firebaseapp.com',
    storageBucket: 'book-buds.appspot.com',
    measurementId: 'G-JRRR5KMSXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvf2Ez9qqZTWTdbKjQvmMkZRo_W--xjY',
    appId: '1:957207033721:android:f7db24eb34f9d5306921a8',
    messagingSenderId: '957207033721',
    projectId: 'book-buds',
    storageBucket: 'book-buds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHIEMwIS2CEtVYizrD5B4xB7vLdLiVNw',
    appId: '1:957207033721:ios:462e5941b24f1cc66921a8',
    messagingSenderId: '957207033721',
    projectId: 'book-buds',
    storageBucket: 'book-buds.appspot.com',
    iosBundleId: 'com.example.bookBuds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHIEMwIS2CEtVYizrD5B4xB7vLdLiVNw',
    appId: '1:957207033721:ios:462e5941b24f1cc66921a8',
    messagingSenderId: '957207033721',
    projectId: 'book-buds',
    storageBucket: 'book-buds.appspot.com',
    iosBundleId: 'com.example.bookBuds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6zCE04v7xPqj3X0gnQhq-sGEEEVRgjE',
    appId: '1:957207033721:web:60b56f86d585ff8e6921a8',
    messagingSenderId: '957207033721',
    projectId: 'book-buds',
    authDomain: 'book-buds.firebaseapp.com',
    storageBucket: 'book-buds.appspot.com',
    measurementId: 'G-9DC1944TDN',
  );

}